### ISSUE TITLE
Cambiar texto en emails (y periodicidad) y aviso al final de la pregunta para incluir los nuevos tiempos.

### ISSUE THREAD

**Issue by EvaBelmonte** [civio/tuderechoasaber-theme#25]
El texto será:

"Tu solicitud ha sido enviada correctamente.
A partir de este momento tienen un mes para contestarte, 15 días si has enviado la solicitud a la Comunidad de Navarra.
Si no te contestan antes, el día que cumpla el plazo que tienen para contestarte tuderechoasaber.es te enviará un email para recordarte que ya ha pasado dicho plazo y te informaremos sobre las posibilidades de recurso que tienes.
Muchas gracias por utilizar tuderechoasaber.es"

**Comment by dcabo** [comment]
Como se repetía "contestar" en "Si no te contestan antes, el día que cumpla el plazo que tienen para contestarte...", he puesto "Si no te contestan antes, el día que se cumpla el plazo legal...". ¿ok?

Por cierto, me he dado cuenta de que en realidad esto no es un correo, este mensaje sale en la parte superior de la página al enviar la pregunta. No hay ningún correo.

**Comment by EvaBelmonte** [comment]
ok  

--  
Eva Belmonte

**Comment by EvaBelmonte** [comment]
El correo es el del mes, no este.   

--  
Eva Belmonte
