### ISSUE TITLE
Que las respuestas del Portal de Transparencia no lleguen a Holding Pen. 

### ISSUE THREAD

**Issue by EvaBelmonte** [civio/tuderechoasaber-theme#26]
Ahora mismo, las respuestas que llegan del portal de transparencia llegan a Holding Pen. Pasa porque el email que recibe la pregunta no es el mismo que el que responde.

**Comment by dcabo** [comment]
I'm quite sure it's because the domain they use doesn't match the one we have on record, since we're pointing to ourselves to handle the process manually. Example:

http://www.tuderechoasaber.es/es/admin/request/show_raw_email/1821

The emails come from noreply.gesat@correo.gob.es

**Comment by dcabo** [comment]
Pues no, no es lo que pensaba, la culpa es de los correos del Portal de Transparencia, que tienen un formato no estándard: no incluyen la dirección de destino en el campo 'To:' o 'Cc:' ni nada. Son muy brutos.
